//////////////////////////////////////////////////////////////////////////////
// RESOURCE.H
//
// Statistics and memory management tool functions for use with the
// Quote package - resource identifiers.
//
// Copyright (c) Ward Quinlan, 1996
//
//////////////////////////////////////////////////////////////////////////////
#define IDD_PERIODDLGPROC  100
#define IDC_PERIOD         101
#define IDD_PERIOD2DLGPROC 102
#define IDC_PERIOD2        103
#define IDD_PERIOD3DLGPROC 104
#define IDC_PERIOD3        105
