###################################
# Budget Led resource script
###################################

# Icons

IDI_BUDGET
IDI_DOCUMENT

# Controls
IDC_DATE
IDC_ACCOUNT
IDC_DESC
IDC_AMOUNT
IDC_VERSION1
IDC_VERSION2
IDC_DEPOSIT
IDC_WITHDRAW
IDC_CREATE
IDC_DELETE
IDC_XFER
IDC_FROM
IDC_TO
IDC_MACRO
IDC_EXECUTE
IDC_SEQ
IDC_SUMMARY
IDC_BALANCE
IDC_CONFIRMTEXT
IDC_DEPOSITTEXT
IDC_BALANCETEXT
IDC_ACCOUNT2

# Dialog Boxes
IDD_CREATEBOX
IDD_TRANSACTIONSBOX
IDD_BALANCEBOX
IDD_ABOUTBOX
IDD_NEWWINDOWBOX
IDD_DELETEBOX
IDD_XFERBOX
IDD_MACROBOX
IDD_CONFIRMBOX

# Accelerator table

IDA_BUDGET

# Menus
IDM_MENUMAIN
IDM_NEW
IDM_OPEN
IDM_SAVE
IDM_SAVEAS
IDM_EXIT
IDM_CREATE
IDM_TRANSACTIONS
IDM_CASCADE
IDM_TILE
IDM_ARRANGE
IDM_TR_OFF         # only on during DEBUG
IDM_TR_NORMAL      # only on during DEBUG
IDM_TR_INTENSE     # only on during DEBUG
IDM_TR_WALKMEMORY  # only on during DEBUG
IDM_TR_CHECKMEMORY # only on during DEBUG
IDM_TR_ASSERTVALID # only on during DEBUG
IDM_TR_MEMORYSTATS # only on during DEBUG
IDM_CALCULATOR
IDM_NEWWINDOW
IDM_ABOUT
IDM_DELETE
IDM_XFER
IDM_MACRO
IDM_BALANCE
IDM_UNBALANCE
IDM_NOOP           # no-op

IDM_FIRSTCHILD     # Note: this must be last!!


