//////////////////////////////////////////////////////////////////////////////
// CCI.HXX
//
// Commodity Channel Index Indicator
//
// This is for use with the Quote package.
// Copyright (c) Ward Quinlan, 1996
//////////////////////////////////////////////////////////////////////////////
extern "C" {
           
int  FAR PASCAL LibMain( HANDLE hInstance, WORD wDataSeg, WORD wHeapSize, LPSTR lpszCmdLine );  
int  FAR PASCAL _export WEP( int nParam );
};
