//////////////////////////////////////////////////////////////////////////////
// DMI.HXX
//
// Directional Movement Indicator
//
// This indicator is for use with the Quote package.
//
// This is an implementation of the Directional Movement
// Indicator, developed by J. Welles Wilder.
//////////////////////////////////////////////////////////////////////////////

#ifndef RC_INVOKED
extern "C" 
    {
    int  FAR PASCAL LibMain( HANDLE hInstance, WORD wDataSeg, WORD wHeapSize, LPSTR lpszCmdLine );  
    int  FAR PASCAL _export WEP( int nParam );
    };
#endif
