//////////////////////////////////////////////////////////////////////////////
// RESOURCE.HXX
//
// Resources defintions.
//
// This is for use with the Quote package.
// Copyright (c) Ward Quinlan, 1996
//////////////////////////////////////////////////////////////////////////////
#ifndef _RESOURCE_HXX
#define _RESOURCE_HXX

// No resources!!

// N.B.  Any dialog box resources must be defined in decimal

#endif

