##############################################################################
## RESOURCES.R
##
## Resource Defintions Led Script
##############################################################################

## String Table

IDS_DEFAULT_TPL
IDS_MDICLIENT
IDS_CLSCHILD
IDS_CLSCHILDTEXT
IDS_CLSCHILDTRADELIST
IDS_CLSCHILDPERFSUM
IDS_TITLETEXT
IDS_TITLETRADELIST
IDS_TITLESIMTRADELIST
IDS_TITLEPERFSUM
IDS_TITLESIMPERFSUM
IDS_EMPTY
IDS_RETURN
IDS_APPNAME
IDS_NOTCORRUPT
IDS_CORRUPT
IDS_TEMPLATENOTFOUND
IDS_CORRUPTTEMPLATE
IDS_CORRUPTDOCUMENT
IDS_QUERYSAVETEMPLATE
IDS_WINDOW_BACKGROUND
IDS_TEXT_FACE
IDS_HI_LO_CLOSE_BAR
IDS_VOLUME_BAR
IDS_GRIDS
IDS_BUY_SIGNAL
IDS_SELL_SIGNAL
IDS_DUMMY
IDS_NAME_EXISTS
IDS_ITPROC_VERSTRING
IDS_ITPROC_PARAMSTRING
IDS_ITPROC_CALC
IDS_ITPROC_OPTIONS
IDS_ITPROC_DEFOPTIONS
IDS_BADINDICATOR
IDS_LOAD_STRING
IDS_LOAD_DELIMITERS
IDS_SAVE_STRING
IDS_FOPEN_RT
IDS_FOPEN_RB
IDS_FOPEN_WT
IDS_FOPEN_WB
IDS_UNTITLED
IDS_REPLACE
IDS_NOPATH
IDS_MEMORY
IDS_BADDXINCR
IDS_BADGRIDS
IDS_BADPERCENT
IDS_BADPERCENT2
IDS_VIEWA
IDS_VIEWB
IDS_VIEWC
IDS_VIEWD
IDS_BADNAME
IDS_UNAVAIL
IDS_BOXCTRL
IDS_SAVEQUERY
IDS_BADVALUE
IDS_QUOTEBOX
IDS_BADDATE
IDS_BADQUOTE
IDS_GENERALERROR
IDS_REMOVE
IDS_INDICATORINUSE
IDS_CONDITIONINUSE
IDS_LAYOUTINUSE
IDS_RULEINUSE
IDS_VERSION
IDS_FILLIN
IDS_NONE
IDS_CANTEVAL  
IDS_POINTFIVE
IDS_DEVICEMODE
IDS_DOTDRV
IDS_WININI_WINDOWS
IDS_WININI_DEVICE
IDS_TEXT_FILE_CORRUPT_AT
IDS_CUSTOM_VERSTRING
IDS_CUSTOM_LIB
IDS_EXTERNAL_VERSTRING
IDS_EXTERNAL_LIB
IDS_SEPARATOR
IDS_POSITIVE
IDS_NOVALUE
IDS_USERCONFIRM
IDS_NET_PROFIT
IDS_ROA
IDS_PROFIT_FACTOR
IDS_AVG_TRADE
IDS_PCT_PROFITABLE
IDS_RATIO_AVGWIN_AVGLOSS
IDS_ACCOUNT_SIZE
IDS_EXTINDFILE_ERROR
IDS_EXTINDFILE_CORRUPT
IDS_BAD_EXPORT
IDS_BAD_SAVE_TEXT
IDS_N_TRADES

## Icons
IDI_QUOTE

## Accelerator Table
IDA_QUOTE

## Menus
IDM_MAIN

IDM_NEW
IDM_OPEN
IDM_SAVE
IDM_SAVEAS
IDM_SAVE_TEXT
IDM_SAVETEMPLATE
IDM_EXPORT_TEMPLATE
IDM_PRINT_SETUP
IDM_PRINT
IDM_EXIT
IDM_LOAD_PREV
IDM_LOAD_NEXT
IDM_NOOP ## no-op

IDM_ADD_QUOTE
IDM_DELETE_QUOTE

IDM_FONT_SIZE
IDM_COLOR
IDM_LINE_WIDTH
IDM_TEXT_FORMAT
IDM_BROWSER
IDM_EXTERNAL_INDICATOR_FILE
IDM_QUOTE_BOX
IDM_TRACKER
IDM_AUTOOPENTEXT
IDM_TEXT_GRID_LINES
IDM_DATES_NONE
IDM_DATES_MONTHS
IDM_DATES_YEARS
IDM_SCR_PAGE
IDM_SCR_CHART
IDM_PRT_PAGE
IDM_PRT_CHART

IDM_CREATE_IT
IDM_CUSTOM_IT
IDM_EXTERNAL_IT
IDM_DELETE_IT
IDM_CREATE_WL
IDM_DELETE_WL
IDM_CREATE_RULE
IDM_DELETE_RULE
IDM_CREATE_COND
IDM_DELETE_COND
IDM_CREATE_CONST
IDM_DELETE_CONST

IDM_PERFORMANCE
IDM_TRADESIM
IDM_CHART_SCANNER
IDM_INDVAL
IDM_CLEAR_PERF_DATA

IDM_CASCADE
IDM_TILE
IDM_ARRANGE_ICONS
IDM_NEW_WINDOW
IDM_NEW_TEXTWINDOW
IDM_NEW_TRADELIST
IDM_NEW_PERFSUM
IDM_NEW_STRADELIST
IDM_NEW_SIMRESULTS

## Tracing Identifiers

IDM_TR_OFF
IDM_TR_NORMAL
IDM_TR_INTENSE
IDM_TR_ASSERTVALID
IDM_TR_WALKMEMORY
IDM_TR_CHECKMEMORY
IDM_TR_MEMORYSTATS
IDM_TR_COUNTQQTS
IDM_DUMP_CACHE
IDM_CLEAR_CACHE
IDM_CONSTANTS

## About Box

IDM_ABOUT

IDM_FIRST_CHILD ## This must be last!!

## Bitmaps

IDB_NEW
IDB_NEW2
IDB_OPEN
IDB_OPEN2
IDB_SAVE
IDB_SAVE2
IDB_SAVETP
IDB_SAVETP2
IDB_PRINT
IDB_PRINT2
IDB_EXIT
IDB_EXIT2
IDB_LP
IDB_LP2
IDB_LN
IDB_LN2
IDB_BLANK
IDB_BLANK2
IDB_CIT
IDB_CIT2
IDB_CSIT
IDB_CSIT2
IDB_XIT
IDB_XIT2
IDB_DIT
IDB_DIT2
IDB_CWL
IDB_CWL2
IDB_DWL
IDB_DWL2
IDB_RULE
IDB_RULE2
IDB_DRULE
IDB_DRULE2
IDB_COND
IDB_COND2
IDB_DCOND
IDB_DCOND2
IDB_CONST
IDB_CONST2
IDB_PERFORMANCE
IDB_PERFORMANCE2
IDB_SIM
IDB_SIM2
IDB_SCANNER
IDB_SCANNER2
IDB_INDVAL
IDB_INDVAL2
IDB_COLOR
IDB_COLOR2
IDB_TEXT
IDB_TEXT2
IDB_NEW_WINDOW
IDB_NEW_WINDOW2
IDB_NEW_TEXTWINDOW
IDB_NEW_TEXTWINDOW2

## Add Quote Dialog Box
IDD_ADD_QUOTE
IDC_DATE
IDC_OP
IDC_HI
IDC_LO
IDC_CL
IDC_VL

## Delete Quote Dialog Box
IDD_DELETE_QUOTE

## Font Size Dialog Box
IDD_FONT_SIZE
IDC_FONT_SIZE

## Browser Dialog Box
IDD_BROWSER
IDC_BROWSER

## External Indicator File Dialog Box
IDD_EXTERNAL_INDICATOR_FILE
IDC_EXTERNAL_INDICATOR_FILE

## Line Width Dialog Box
IDD_LINE_WIDTH
IDC_LINE_WIDTH

## New Window Dialog Box
IDD_NEW_WINDOW
IDC_MAXIMIZED

## Color Dialog Box
IDD_COLOR
IDC_COLOR
IDC_ATTRIBUTE

## About Dialog Box
IDD_ABOUT
IDC_VERSION
IDC_COPYRIGHT

## Text File Format Dialog Box
IDD_TEXT_FORMAT
IDC_LOAD_STRING
IDC_LOAD_DELIMITERS
IDC_SAVE_STRING

## Create Indicator Template Dialog Box
IDD_CREATE_IT
IDC_TEMPLATE
IDC_RESERVED
IDC_PATH
IDC_LINE
IDC_BAR
IDC_POINT
IDC_OPTIONS

## Custom Indicator Template Dialog Box
IDD_CUSTOM_IT
IDC_DEFN
IDC_HORZ

## External Indicator Template Dialog Box
IDD_EXTERNAL_IT

## Delete Indicator Template Dialog Box
IDD_DELETE_IT

## Create Condition Dialog Box
IDD_CREATE_COND
IDC_CONDITION

## Delete Condition Dialog Box
IDD_DELETE_COND

## Create Constant Dialog Box
IDD_CREATE_CONST
IDC_CONST

## Delete Constant Dialog Box
IDD_DELETE_CONST

## Create Window Layout Dialog Box
IDD_CREATE_WL
IDC_LAYOUT
IDC_AUTO_OPEN
IDC_DXINCR
IDC_VIEW_TITLE
IDC_EXCLUDE
IDC_INCLUDE
IDC_INCLUDE_PUSH
IDC_EXCLUDE_PUSH
IDC_SHOW_HLC
IDC_SHOW_HG
IDC_GRIDSPERAXIS
IDC_REALESTATE
IDC_A
IDC_B
IDC_C
IDC_D
IDC_ROUNDSCALING
IDC_LOGSCALING

## Delete Window Layout Dialog Box
IDD_DELETE_WL

## Create Rule Dialog Box
IDD_CREATE_RULE
IDC_RULE
IDC_BUY
IDC_FILTER
IDC_FILTER2
IDC_SELL
IDC_CURRENT_CLOSE
IDC_NEXT_OPEN

## Delete Rule Dialog Box
IDD_DELETE_RULE

## Performance Testing Dialog Box
IDD_PERFORMANCE
IDC_LOADED_COMPANY
IDC_ALL_COMPANIES
IDC_POSITION
IDC_COMMISSION
IDC_FILE_EXT
IDC_CONST1
IDC_START1
IDC_STEP1
IDC_N1
IDC_CONST2
IDC_START2
IDC_STEP2
IDC_N2
IDC_CONST3
IDC_START3
IDC_STEP3
IDC_N3
IDC_SORT_BY

## Trade Simulator Dialog Box
IDD_TRADESIM
IDC_INITIAL_ACCOUNT

## Report Scan Results Dialog Box
IDD_REPORT_SCAN_RESULTS
IDC_RESULTS

## Report Indicator Value Results Dialog Box
IDD_REPORT_INDICATORVALUE_RESULTS

## Indicator Value Dialog Box
IDD_INDICATOR_VALUE

## Report Results Dialog Box
IDD_REPORT_RESULTS

IDC_RATIOWINLOSS
IDC_PERCENTPROFITABLE
IDC_RESULT
IDC_RESULT2

IDC_TRADES
IDC_AVERAGEDAYS
IDC_AVERAGETRADE
IDC_ANNUALTRADE
IDC_ANNUALTRADE2

IDC_TRADESWIN
IDC_AVERAGEDAYSWIN
IDC_AVERAGETRADEWIN
IDC_LARGESTWIN

IDC_TRADESLOSS
IDC_AVERAGEDAYSLOSS
IDC_AVERAGETRADELOSS
IDC_LARGESTLOSS

## Save Chart Scanner Results
IDD_SAVE_SCAN_RESULTS

## Print Dialog Box
IDD_PRINT
IDC_TOP
IDC_LEFT
IDC_BOTTOM
IDC_RIGHT
IDC_LASTPAGEONLY

## Chart Scanner Box
IDD_CHART_SCANNER
IDC_BUYS
IDC_SELLS
IDC_BOTH
IDC_DAYS
